package com.zidio.zidioconnect.exception;

public class UserNameNOTFOUNDException extends RuntimeException{
    public UserNameNOTFOUNDException(String userNotFound) {
    }
}
